import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return [
      {
        id: 1,
        name: "Ember",
        website: "http://emberjs.com",
        logoUrl: "http://i.imgur.com/b74CDWt.png",
        stars: 1244,
        jobs: 40,
        size: 38,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 2,
        name: "Angular",
        website: "http://angular.com",
        logoUrl: "http://i.imgur.com/qqZNCEe.png",
        stars: 543,
        jobs: 70,
        size: 43,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 3,
        name: "React",
        website: "http://react.com",
        logoUrl: "http://i.imgur.com/XVCfKgG.png",
        stars: 1403,
        jobs: 75,
        size: 233,
        jsIndex: 79,
        demand: 54,
        maturity: 4,
        future: 23
      },
      {
        id: 4,
        name: "Angular 2",
        website: "http://meteor.com",
        jobs: 10,
        size: 134,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 5,
        name: "Elm",
        website: "http://elm.com",
        jobs: 3,
        size: 134,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 4,
        name: "Meteor",
        website: "http://meteor.com",
        jobs: 10,
        size: 134,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 4,
        name: "Cycle",
        website: "http://meteor.com",
        jobs: 10,
        size: 134,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      },
      {
        id: 4,
        name: "Polymer",
        website: "http://meteor.com",
        jobs: 10,
        size: 134,
        jsIndex: 82,
        demand: 53,
        maturity: 32,
        sizeNormalized: 64,
        performance: 32,
        availableDevelopers: 52,
        addOns: 74,
        future: 31,
        developerExperience: 43,
        documentation: 34,
        community: 32
      }
    ]
  }
});
